baseURL = "http://discountcarpetbrokersaz.netlify.app"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
themesDir = "../.."
title = "Discount Carpet Brokers"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 Discount Carpet Brokers All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "/"
name = "Home"
weight = "1"
[[Languages.en.menu.footer]]
URL = "carpet"
name = "Carpet"
weight = "2"
[[Languages.en.menu.footer]]
URL = "flooring"
name = "Flooring"
weight = "3"
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = "4"
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = "5"
[[Languages.en.menu.footer]]
URL = "blog"
name = "Blog"
weight = "6"
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "carpet"
name = "Carpet"
weight = "2"
[[Languages.en.menu.main]]
URL = "flooring"
name = "Flooring"
weight = "3"
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = "4"
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = "5"
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = "6"
[Languages.fr]
contentDir = ""
copyright = ""
languageCode = ""
languageName = ""
weight = ""
[Languages.fr.menu]
footer = []
main = []
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "demo@email.com"
google_analitycs_id = ""
location = "North Main Street,Brooklyn Australia"
logo = "images/logo.png"
logo_width = "150px"
mobile = "0124857985320"
multi_author = false
[params.cookies]
enable = true
expire_days = 2
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
